obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.24,-0.28],[-0.24,0.28],[0.24,0.28],[0.24,-0.28]]

inflation_radius: 2.5
cost_scaling_factor: 2.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: carter_lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
