obstacle_range: 3.0
raytrace_range: 3.5

footprint: [ [ -0.205, -0.155 ], [ -0.205, 0.155 ], [ 0.077, 0.155 ], [ 0.077, -0.155 ] ]
#robot_radius: 0.17

inflation_radius: 2.5
cost_scaling_factor: 2.0

map_type: costmap
global_frame: map
robot_base_frame: base_link

update_frequency: 1.0
publish_frequency: 10.0
transform_tolerance: 0.5

static_map: true
plugins:
  - {name: static_map,       type: "costmap_2d::StaticLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}